#madlibs
body_part1 = input("Enter a body part: ")
adjective1 = input("Enter an adjective: ")
noun = input("Enter a noun: ")
body_part2 = input("Enter a body part: ")
noun1 = input("Enter a noun: ")
body_part3 = input("Enter a body part: ")
verb = input("Enter a verb ending with s: ")
body_part4 = input("Enter a body part: ")
body_part5 = input("Enter a body part: ")
verb2 =  input("Enter a verb: ")
body_part6 = input("Enter a body part: ")
adjective2 = input("Enter an adjective: ")
noun2 = input("Enter a noun: ")
verb3 = input("Enter a verb ending with -ing: " )
adjective3 = input("Enter an adjective: ")
body_part7 = input("Enter a bodypart: ")
verb4 = input("Enter a verb ending with s: ")
intense = input("Enter a percentage: ")

print("Here's a story")
print(body_part1 + ". With one " + adjective1 + " movement ,he angles his")
print(noun + " so my " + body_part2 + " is resting on the "+ noun1 + " beside")
print("him. He throws his right " + body_part3 + " over mine and ")
print(verb + " his left " + body_part4 + " on the back of my " + body_part5)
print("holding me down so i cannot " + verb2 + ". . . He places")
print("his "+ body_part6 + " on my " + adjective2 + " " + noun2 +", softly " + verb3 + " me,")
print("stroking around and around with his " + adjective3 + "palm.")
print("And then his " + body_part7 + " is no longer there ... and he")
print(verb4 + " me -" + intense + ".")
print("THE END...")
print(" ")
print(" ")

